# Generated by Django 4.2.2 on 2024-01-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycart',
            name='test',
        ),
        migrations.AddField(
            model_name='mycart',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserApp.status'),
            preserve_default=False,
        ),
    ]
